{
 "title": "amd cpu/gpu stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "gpu info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "amdgpu_detailed_info" }
   ]
  },
  {
   "title": "power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ryzenadj_stapm_value", "legendFormat": "{{__name__}}" },
    { "expr": "ryzenadj_stapm_limit", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "ryzenadj_tctl_temp_value", "legendFormat": "{{__name__}}" },
    { "expr": "amdgpu_temperature", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "VRAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "amdgpu_vram_usage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "gpu-clock",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "amdgpu_sclk", "legendFormat": "{{__name__}}" },
    { "expr": "amdgpu_max_clocks_sclk_max", "legendFormat": "{{__name__}}" },
    { "expr": "amdgpu_mclk", "legendFormat": "{{__name__}}" },
    { "expr": "amdgpu_max_clocks_mclk_max", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "vrmmax_current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "ryzenadj_vrmmax_current_value", "legendFormat": "{{__name__}}" },
    { "expr": "ryzenadj_vrmmax_current", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}