{
 "title": "aria2",
 "tags": [ "network" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "aria2_global_downloadSpeed", "legendFormat": "Download: total" },
    { "expr": "aria2_global_uploadSpeed", "legendFormat": "Upload: total" },
    { "expr": "aria2_task_uploadSpeed>0", "legendFormat": "Upload: {{name}}" },
    { "expr": "aria2_task_downloadSpeed>0", "legendFormat": "Download: {{name}}" }
   ]
  },
  {
   "title": "task nums",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "aria2_global_numActive", "legendFormat": "{{__name__}}" },
    { "expr": "aria2_global_numStopped", "legendFormat": "{{__name__}}" },
    { "expr": "aria2_global_numWaiting", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "task progress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1>(aria2_task_completedLength/aria2_task_totalLength)>0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "peer num",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "aria2_task_numSeeders{name!=\"\",bittorrent=\"1\"}>0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "aria2_task_connections{name!=\"\",bittorrent=\"0\"}>0",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}