{
 "title": "s-tui",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(s_tui_sensors_Util{}, instance)"
    }
   },
   { "name": "times" }
  ]
 },
 "panels": [
  {
   "title": "s_tui_sensors_Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "s_tui_sensors_Power{instance=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "s_tui_sensors_Util",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "s_tui_sensors_Util{instance=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "s_tui_sensors_Frequency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "(s_tui_sensors_Frequency{instance=\"$node\"}*1000000 and on() (s_tui_sensors_Fan{instance=\"$node\"}>0)) or on() s_tui_sensors_Frequency{instance=\"$node\"}*1000000000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "s_tui_sensors_Temp",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "s_tui_sensors_Temp{device!~\"Auxtin.*|Sensor.*|Systin.*\",instance=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "s_tui_sensors_Fan",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "s_tui_sensors_Fan{instance=\"$node\"}>0",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}