{
 "title": "tplink",
 "tags": [ "network" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "device types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(tplink_host_info_detail{type=\"1\",wifi_mode=\"0\",blocked=\"0\"})",
     "legendFormat": "2.4g devices"
    },
    {
     "expr": "count(tplink_host_info_detail{type=\"1\",wifi_mode=\"1\",blocked=\"0\"})",
     "legendFormat": "5g devices"
    },
    {
     "expr": "count(tplink_host_info_detail{type=\"0\",wifi_mode=\"0\",blocked=\"0\"})",
     "legendFormat": "wired devices"
    }
   ]
  },
  {
   "title": "wired ports status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "tplink_port_manage_phy_info", "legendFormat": "port{{phy}}: {{role}}" }
   ]
  },
  {
   "title": "lan devices online",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "tplink_host_info_detail{blocked=\"0\"}",
     "legendFormat": "{{mac}}"
    }
   ]
  },
  {
   "title": "wan uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tplink_wan_status_up_time" }
   ]
  },
  {
   "title": "wanv6 uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tplink_wanv6_status_up_time" }
   ]
  },
  {
   "title": "hardware info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    { "expr": "tplink_port_manage_dev_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ipv4 wan status",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 10 },
   "repeat": "Filters",
   "targets": [
    { "expr": "tplink_wan_status_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ipv6 wan status",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 10 },
   "targets": [
    { "expr": "tplink_wanv6_status_info{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Monitors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "traffic monitor",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (ip,hostname,mac) (tplink_host_info_down_speed{ip!~\"0.0.0.0|169.254.*\"}) ",
     "legendFormat": "Download: {{hostname}}({{ip}})"
    },
    {
     "expr": "sum by (ip,hostname,mac) (tplink_host_info_up_speed{ip!~\"0.0.0.0|169.254.*\"})",
     "legendFormat": "Upload: {{hostname}}({{ip}})"
    },
    {
     "expr": "tplink_wan_status_up_speed*1024",
     "legendFormat": "Upload: total"
    },
    {
     "expr": "tplink_wan_status_down_speed*1024",
     "legendFormat": "Download: total"
    }
   ]
  },
  {
   "title": "device nums",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "tplink_cap_host_num", "legendFormat": "host devices" },
    { "expr": "tplink_cap_guest_num", "legendFormat": "guest devices" },
    {
     "expr": "count(tplink_host_info_detail{wifi_mode=\"1\",blocked=\"0\"})",
     "legendFormat": "wifi 5g devices"
    },
    {
     "expr": "count(tplink_host_info_detail{type=\"0\",blocked=\"0\"})",
     "legendFormat": "wired devices"
    },
    {
     "expr": "count(tplink_host_info_detail{type=\"1\",wifi_mode=\"0\",blocked=\"0\"})",
     "legendFormat": "2.4g devices"
    }
   ]
  },
  {
   "title": "upnp lease",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "count (tplink_upnpd_upnp_lease) by (client,desc)",
     "legendFormat": "{{client}}: {{desc}}"
    }
   ]
  },
  {
   "title": "dhcp lease",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "tplink_dhcpd_dhcp_clients{}<86400",
     "legendFormat": "{{hostname}}({{ip}})"
    }
   ]
  },
  {
   "title": "lease detail info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "current upnp lease",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
     "targets": [
      { "expr": "tplink_upnpd_upnp_lease" }
     ]
    },
    {
     "title": "current dhcp lease",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      { "expr": "tplink_dhcpd_dhcp_clients" }
     ]
    }
   ]
  },
  {
   "title": "logs&msgs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "syslog",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "avg(tplink_system_logs) by (level,text,name)"
      }
     ]
    },
    {
     "title": "pushed msgs",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 44 },
     "targets": [
      { "expr": "tplink_realtime_push_msg" }
     ]
    }
   ]
  }
 ]
}