{
 "title": "viewpower",
 "tags": [ "UPS" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "UPS work mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "viewpower_workInfo_info" }
   ]
  },
  {
   "title": "electricty used in last 30 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(viewpower_outputLoadPercent[30d])*5*9/3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eletricity used per days",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time(viewpower_outputLoadPercent[$__interval])*5*9/3600",
     "legendFormat": "eletricity used"
    }
   ]
  },
  {
   "title": "voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "viewpower_inputVoltage>0", "legendFormat": "inputVoltage" },
    { "expr": "viewpower_outputVoltage>0", "legendFormat": "outputVoltage" },
    { "expr": "viewpower_batteryVoltage>0", "legendFormat": "batteryVoltage" }
   ]
  },
  {
   "title": "power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "viewpower_outputLoadPercent*9", "legendFormat": "power" }
   ]
  },
  {
   "title": "load/battery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "viewpower_outputLoadPercent", "legendFormat": "outputLoadPercent" },
    { "expr": "viewpower_batteryCapacity>0", "legendFormat": "batteryCapacity" }
   ]
  }
 ]
}